version: '3.8'

services:
  web:
    build:
      context: ./t24
      dockerfile: ./dev.Dockerfile
    command: venv/bin/python manage.py runserver localhost:${APP_PORT}
    hostname: 'localhost'
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/app
    env_file:
      - env/dev.env
      - env/dev.db.env
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - env/dev.db.env

volumes:
  postgres-data: