version: '3.8'

services:
  web:
    image: nvidia/cuda:12.3.1-base-ubuntu22.04
    mem_reservation:
      8g
    env_file:
      - env/dev.env
      - env/dev.db.env
    build:
      context: .
      dockerfile: ./t24/dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#    depends_on:
#      - db
#  db:
#    image: postgres:15.3-alpine
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    env_file:
#      - env/dev.db.env
#
#volumes:
#  postgres-data: