# Generated by Django 5.1.2 on 2024-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boltalka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='input_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
